#!/bin/sh

set -e
export CC=gcc

echo "==> Installing gem dependecies…"

# bundle check --path vendor/gems 2>&1 > /dev/null || {
#   bundle install --binstubs bin --path vendor/gems --local --quiet
# }

bundle install
